swagger: "2.0"
info:
  version: '1.0.0'
  title: Digital Bank API
  description: API for managing a digital bank in Madagascar
basePath: /api
tags:
  - name: Accounts
    description: Operations related to bank accounts
  - name: Customer Portfolio
    description: Operations related to customer portfolio
schemes:
  - https
paths:
  /accounts:
    get:
      summary: List of accounts
      tags:
        - Accounts
      responses:
        '200':
          description: List of accounts retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Account'
    post:
      summary: Create an account
      tags:
        - Accounts
      parameters:
        - in: body
          name: body
          description: Information of the new account
          required: true
          schema:
            $ref: '#/definitions/AccountInput'
      responses:
        '201':
          description: Account created successfully
          schema:
            $ref: '#/definitions/Account'
  /accounts/{id}:
    get:
      summary: Account details
      tags:
        - Accounts
      parameters:
        - name: id
          in: path
          description: ID of the account to retrieve
          required: true
          type: string
      responses:
        '200':
          description: Account details retrieved successfully
          schema:
            $ref: '#/definitions/Account'
    put:
      summary: Modify an account
      tags:
        - Accounts
      parameters:
        - name: id
          in: path
          description: ID of the account to modify
          required: true
          type: string
        - in: body
          name: body
          description: Information of the account to modify
          required: true
          schema:
            $ref: '#/definitions/AccountInput'
      responses:
        '200':
          description: Account modified successfully
          schema:
            $ref: '#/definitions/Account'
  /accounts/{id}/balance:
    get:
      summary: Check account balance
      tags:
        - Accounts
      parameters:
        - name: id
          in: path
          description: ID of the account to check
          required: true
          type: string
      responses:
        '200':
          description: Account balance retrieved successfully
          schema:
            type: object
            properties:
              balance:
                type: number
                description: Current balance of the account
  /accounts/{id}/transfers:
    post:
      summary: Perform a transfer
      tags:
        - Accounts
      parameters:
        - name: id
          in: path
          description: ID of the source account
          required: true
          type: string
        - in: body
          name: body
          description: Transfer information
          required: true
          schema:
            $ref: '#/definitions/TransferInput'
      responses:
        '200':
          description: Transfer performed successfully
  /accounts/{id}/withdrawals:
    post:
      summary: Perform a cash withdrawal
      tags:
        - Accounts
      parameters:
        - name: id
          in: path
          description: ID of the account to debit
          required: true
          type: string
        - in: body
          name: body
          description: Withdrawal information
          required: true
          schema:
            $ref: '#/definitions/WithdrawalInput'
      responses:
        '200':
          description: Withdrawal performed successfully
definitions:
  Account:
    type: object
    properties:
      id:
        type: string
        description: Unique ID of the account
      name:
        type: string
        description: Name of the client
      first_name:
        type: string
        description: First name(s) of the client
      date_of_birth:
        type: string
        format: date
        description: Date of birth of the client (in YYYY-MM-DD format)
      monthly_net_salary:
        type: number
        description: Client's monthly net salary
    required:
      - name
      - first_name
      - date_of_birth
      - monthly_net_salary
  AccountInput:
    type: object
    properties:
      name:
        type: string
        description: Name of the client
      first_name:
        type: string
        description: First name(s) of the client
      date_of_birth:
        type: string
        format: date
        description: Date of birth of the client (in YYYY-MM-DD format)
      monthly_net_salary:
        type: number
        description: Client's monthly net salary
    required:
      - name
      - first_name
      - date_of_birth
      - monthly_net_salary
  TransferInput:
    type: object
    properties:
      amount:
        type: number
        description: Transfer amount
      beneficiary:
        type: string
        description: ID of the beneficiary account
      reason:
        type: string
        description: Reason for the transfer
    required:
      - amount
      - beneficiary
      - reason
  WithdrawalInput:
    type: object
    properties:
      amount:
        type: number
        description: Withdrawal amount
      source_account:
        type: string
        description: ID of the account from which to withdraw
      date_time:
        type: string
        format: date-time
        description: Date and time of the withdrawal
    required:
      - amount
      - source_account
      - date_time
